# Generated by Django 6.0.6 on 2026-09-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("pet_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "pet_name",
                    models.CharField(max_length=100, verbose_name="Pet / Breed Name"),
                ),
                (
                    "species",
                    models.CharField(
                        default="Dog", max_length=50, verbose_name="Species"
                    ),
                ),
                ("breed", models.CharField(max_length=100, verbose_name="Breed")),
                ("pet_description", models.TextField(verbose_name="Pet Description")),
                (
                    "basic_info_summary",
                    models.TextField(verbose_name="Basic Info Summary"),
                ),
                (
                    "detailed_bio",
                    models.TextField(verbose_name="Detailed Bio / Personality"),
                ),
                (
                    "species_care_needs",
                    models.TextField(verbose_name="Species Care Needs"),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Special Health & Care Requirements",
                    ),
                ),
                (
                    "general_availability",
                    models.CharField(
                        choices=[("Common", "Common"), ("Specialized", "Specialized")],
                        default="Common",
                        max_length=50,
                        verbose_name="General Availability",
                    ),
                ),
                (
                    "size_category",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        default="Small",
                        max_length=50,
                        verbose_name="Size Category",
                    ),
                ),
                (
                    "min_budget",
                    models.IntegerField(
                        default=1000, verbose_name="Min Monthly Budget (THB)"
                    ),
                ),
                (
                    "max_budget",
                    models.IntegerField(
                        default=5000, verbose_name="Max Monthly Budget (THB)"
                    ),
                ),
                (
                    "shedding_level",
                    models.CharField(
                        default="Low", max_length=50, verbose_name="Shedding Level"
                    ),
                ),
                (
                    "energy_level",
                    models.CharField(
                        default="Medium", max_length=50, verbose_name="Energy Level"
                    ),
                ),
                (
                    "beginner_friendly",
                    models.BooleanField(default=True, verbose_name="Beginner Friendly"),
                ),
                (
                    "apartment_friendly",
                    models.BooleanField(
                        default=True, verbose_name="Apartment / Condo Friendly"
                    ),
                ),
                (
                    "suitable_owner_type",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Suitable Owner Lifestyle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "db_table": "pet",
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "overall_compatibility_score",
                    models.FloatField(
                        default=0.0, verbose_name="Overall Compatibility Score (%)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
            ],
            options={
                "verbose_name": "Result",
                "verbose_name_plural": "Results",
                "db_table": "result",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Full Name"),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="PetPhoto",
            fields=[
                ("photo_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_url",
                    models.CharField(max_length=500, verbose_name="Image URL"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary Photo"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[("Profile", "Profile"), ("Detailed", "Detailed")],
                        default="Profile",
                        max_length=50,
                        verbose_name="Photo Type",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="web.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet Photo",
                "verbose_name_plural": "Pet Photos",
                "db_table": "pet_photo",
            },
        ),
        migrations.CreateModel(
            name="TopPetRecommendation",
            fields=[
                (
                    "recommendation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("rank", models.IntegerField(default=1, verbose_name="Rank (1-3)")),
                ("matching_reason", models.TextField(verbose_name="Matching Reason")),
                (
                    "matching_score",
                    models.FloatField(default=0.0, verbose_name="Matching Score (%)"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="web.pet",
                        verbose_name="Pet",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="web.result",
                        verbose_name="Result",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top Pet Recommendation",
                "verbose_name_plural": "Top Pet Recommendations",
                "db_table": "top_pet_recommendation",
            },
        ),
        migrations.CreateModel(
            name="UserMatchingProfile",
            fields=[
                (
                    "user_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "residence_type",
                    models.CharField(max_length=100, verbose_name="Residence Type"),
                ),
                (
                    "residence_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Residence Details"
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        max_length=100, verbose_name="Monthly Budget Range"
                    ),
                ),
                (
                    "available_time_daily",
                    models.CharField(
                        max_length=100, verbose_name="Daily Available Time"
                    ),
                ),
                (
                    "pet_care_experience",
                    models.CharField(
                        max_length=100, verbose_name="Pet Care Experience"
                    ),
                ),
                (
                    "preferred_pet_type",
                    models.CharField(
                        default="Dog", max_length=100, verbose_name="Preferred Pet Type"
                    ),
                ),
                (
                    "additional_preferences",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Preferences"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_profiles",
                        to="web.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Matching Profile",
                "verbose_name_plural": "User Matching Profiles",
                "db_table": "user_matching_profile",
            },
        ),
        migrations.AddField(
            model_name="result",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="web.usermatchingprofile",
                verbose_name="Matching Profile",
            ),
        ),
    ]
